### ISSUE TITLE
Bug on lesson opening

### ISSUE THREAD

**Issue by CPASimUSante** [iCAPLyon1/LessonBundle#11]
I create a lesson and just when i click on the resource (nothing more), i've got : 
```
Impossible to access an attribute ("id") on a null variable in IcapLessonBundle:Lesson:viewChapter.html.twig at line 8
500 Internal Server Error - Twig_Error_Runtime
``` 
Tested on V5 / V6 !

**Comment by maxailloud** [comment]
Fixed by https://github.com/iCAPLyon1/LessonBundle/commit/c7dc7a5627d464ad6ff5c4ee7e099f9863626676 and https://github.com/iCAPLyon1/LessonBundle/commit/28d1258ffb5bb72cd4a82724284f9afb0fe0a6a3

**Comment by CPASimUSante** [comment]
Thank you
